set(EIGEN_INCLUDE_DIR "/usr/include/eigen3" CACHE PATH "Path to Eigen include directory")
set(CMAKE_CUDA_PATH "" CACHE PATH "Optional path to CUDA installation")
set(GUROBI_ROOT "" CACHE PATH "Path to Gurobi installation")
set(HIGHS_ROOT "" CACHE PATH "Path to HiGHS installation (or build directory)")
option(ENABLE_CUPDLPX "Enable cuPDLPx solver for LP" ON)
option(ENABLE_GUROBI "Enable Gurobi solver for LP and assignment subproblems" ON)
option(ENABLE_HIGHS "Enable HiGHS solver for fair assignment subproblems" ON)
set(CUPDLPX_ROOT "" CACHE PATH "Path to cuPDLPx installation")
set(CUPDLPX_BUILD_DIR "" CACHE PATH "Path to cuPDLPx build directory")