set(EIGEN_INCLUDE_DIR "/usr/include/eigen3/" CACHE PATH "Path to Eigen include directory")
set(CMAKE_CUDA_PATH "/usr/local/cuda-12.5/" CACHE PATH "Path to CUDA installation")
set(GUROBI_ROOT "" CACHE PATH "Path to Gurobi installation")
option(ENABLE_CUPDLPX "Enable cuPDLPx solver for LP" ON)
option(ENABLE_GUROBI "Enable Gurobi solver for LP" OFF)
set(CUPDLPX_ROOT "" CACHE PATH "Path to cuPDLPx installation")